[package]
name = "samrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mybin"
path = "src/bin.rs"


[dependencies]
ahash = "0.8.11"
derive_more = "0.99.17"
nalgebra = "0.32.5"
num-dual = "0.9.1"
