[package]
name = "samrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mybin"
path = "src/bin.rs"


[dependencies]
ahash = "0.8.11"
derive_more = "0.99.17"
paste = "1.0.15"

faer = { version = "0.19.0", default-features = false, features = ["perf-warn", "rayon", "std"] }
faer-ext = { version = "0.2.0", features = ["nalgebra"] }
nalgebra = { version = "0.32.5", features = ["compare"] }
num-dual = "0.9.1"
matrixcompare-core = { version = "0.1", optional = true }
serde = {version = "1.0.203", optional = true }
log = "0.4.21"


[features]
f32 = []
left = []
compare = ["dep:matrixcompare-core", "nalgebra/compare", "faer/matrixcompare"]
serde = ["dep:serde", "nalgebra/serde", "faer/serde", "ahash/serde"]

[dev-dependencies]
matrixcompare = "0.3.0"
pretty_env_logger = "0.4"