[package]
name = "samrs"
version = "0.1.0"
edition = "2021"

[dependencies]
# base
ahash = "0.8.11"
derive_more = "0.99.17"
paste = "1.0.15"
downcast-rs = "1.2.1"
log = "0.4.21"
log = "0.4.21"

# numerical 
faer = { version = "0.19.0", default-features = false, features = ["perf-warn", "std"] }
faer-ext = { version = "0.2.0", features = ["nalgebra"] }
nalgebra = { version = "0.32.5" }
num-dual = "0.9.1"
matrixcompare-core = { version = "0.1", optional = true }

# serialization
serde = {version = "1.0.203", optional = true }
typetag = {version = "0.2.16", optional = true }

# rerun support
rerun = { version = "0.16.1", optional = true}

[features]
f32 = []
left = []
fake_exp = []
compare = ["dep:matrixcompare-core", "nalgebra/compare", "faer/matrixcompare"]
serde = ["dep:serde", "dep:typetag", "nalgebra/serde-serialize", "faer/serde", "ahash/serde"]
multithread = ["faer/rayon"]
rerun = ["dep:rerun"]

[dev-dependencies]
matrixcompare = "0.3.0"
pretty_env_logger = "0.4"
nalgebra = { version = "0.32.5", features = ["compare"] }

[[example]]
name = "g2o"

[[example]]
name = "g2o-rerun"
required-features = ["rerun"]

[[example]]
name = "serde"
required-features=["serde"]
