[package]
name = "samrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mybin"
path = "src/bin.rs"


[dependencies]
ahash = "0.8.11"
derive_more = "0.99.17"
matrixcompare = "0.3.0"
nalgebra = { version = "0.32.5", features = ["compare"] }
num-dual = "0.9.1"
paste = "1.0.15"

[features]
f32 = []
left = []
