[package]
name = "samrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mybin"
path = "src/bin.rs"


[dependencies]
ahash = "0.8.11"
derive_more = "0.99.17"
enum_dispatch = "0.3.13"
nalgebra = "0.32.5"
try_as = { version = "0.1.0", git = "https://github.com/contagon/try_as" }
