[package]
name = "factrs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Factor graph optimization for robotics"
readme = "README.md"
authors = ["Easton Potokar", "Taylor Pool"]
repository = "https://github.com/rpl-cmu/factrs"
keywords = ["nonlinear", "optimization", "robotics", "estimation", "SLAM"]
categories = ["science::robotics", "mathematics"]
rust-version = "1.83"
exclude = ["examples/data/*"]

[workspace]
members = ["factrs-bench", "factrs-proc"]
exclude = ["factrs-typetag"]

[package.metadata.docs.rs]
features = ["serde", "rerun"]
rustdoc-args = [
    "--cfg",
    "docsrs",
    "--html-in-header",
    "assets/katex-header.html",
]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]


[dependencies]
foldhash = "0.1.4"
paste = "1.0.15"
downcast-rs = "2.0.1"
log = "0.4.22"
factrs-proc = { version = "0.1.0", path = "./factrs-proc" }
pad-adapter = "0.1.1"

# numerical 
faer = { version = "0.20.2", default-features = false, features = [
    "perf-warn",
    "std",
    "linalg",
] }
faer-ext = { version = "0.4.1", features = ["nalgebra"] }
nalgebra = { version = "0.33.2", features = ["compare"] }
num-dual = "0.11.0"
matrixcompare = { version = "0.3.0" }

# serialization
serde = { version = "1.0.217", optional = true }
typetag = { version = "0.2.18", optional = true, path = "./factrs-typetag" }

# rerun support
rerun = { version = "0.21.0", optional = true, default-features = false, features = [
    "sdk",
] }
simba = { version = "0.9.0", default-features = false }
dyn-clone = "1.0.17"


[features]
# Run everything with f32 instead of the default f64
f32 = []

# Use left instead of right for lie group updates
left = []

# use SO(n) x R instead of SE(n) for exponential map
fake_exp = []

# Add multithreaded support (may run slower on smaller problems)
rayon = ["faer/rayon"]

# Add support for serialization
serde = [
    "dep:serde",
    "dep:typetag",
    "factrs-proc/serde",
    "nalgebra/serde-serialize",
]

# Support for conversion to rerun variable types
rerun = ["dep:rerun"]

[dev-dependencies]
matrixcompare = "0.3.0"
pretty_env_logger = "0.5.0"
nalgebra = { version = "0.33.2", features = ["compare"] }
serde_json = { version = "1.0.135" }

[profile.bench]
lto = true

[profile.profile]
inherits = "bench"
debug = true

[profile.dev.package.faer]
opt-level = 3

[[example]]
name = "serde"
required-features = ["serde"]
doc-scrape-examples = true
