[package]
name = "factrs-proc"
version = "0.1.0"
edition = "2021"

[lib]
name = "factrs_proc"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.87"
