[package]
name = "factrs-proc"
version = "0.2.0"
edition = "2021"

[lib]
name = "factrs_proc"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }

[features]
serde = []
