[package]
name = "factrs-bench"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
diol = "0.8.3"
factrs = { version = "0.1.0", path = ".." }
tiny-solver = "0.12.0"
nalgebra = { version = "0.33.2", features = ["compare"] }

[[bench]]
name = "g2o"
harness = false
